### ISSUE TITLE
Symfony 3.1.*

### ISSUE THREAD

**Issue by Appsido** [ForestAdmin/forest-symfony#1]
So far the bundle is not available for symfony 3.1.*

Is it possible to upgrade to make it available ?

Thanks

**Comment by SeyZ** [comment]
Hey @Appsido `forest-symfony` is in alpha and not yet ready for production. We've release a framework-agnostic way to have your Forest admin interface: https://github.com/ForestAdmin/lumber

**Comment by Appsido** [comment]
@SeyZ yes as you can see i'm aware of the lumber framework :) Anyway i hope the symfony version will be release soon. Great job
